/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent.of.code


fun main() {
  Day6.answers()
  Day7.answers()
  Day8.answers()
  Day9.answers()
  Day10.answers()
}
